
import { FanficWork } from '../types';

export const BORUTO: FanficWork = {
  id: 'boruto',
  title: 'Boruto: Naruto Next Generations',
  description: 'Hậu truyện của Naruto, xoay quanh thế hệ nhẫn giả mới trong thời đại hòa bình và công nghệ.',
  country: 'Nhật',
  plot: 'Nhiều năm sau Đại chiến Nhẫn giả lần thứ tư, Naruto Uzumaki đã trở thành Hokage đệ Thất. Làng Lá giờ đây là một đô thị hiện đại với công nghệ tiên tiến. Boruto Uzumaki, con trai của Naruto, cảm thấy bị bỏ rơi bởi người cha bận rộn và quyết tâm đi theo con đường riêng của mình. Tuy nhiên, một mối đe dọa mới từ gia tộc Otsutsuki và tổ chức bí ẩn Kara đang dần lộ diện, đe dọa nền hòa bình khó khăn lắm mới có được.',
  worldSetting: 'Thế giới nhẫn giả hiện đại hóa, nơi nhẫn thuật kết hợp với khoa học kỹ thuật (Nhẫn cụ khoa học). Các làng nhẫn giả chung sống hòa bình nhưng vẫn đối mặt với các thế lực ngoài hành tinh và các thí nghiệm di truyền nguy hiểm.',
  characters: [
    { name: 'Boruto Uzumaki', role: 'Nhân vật chính', description: 'Con trai của Naruto và Hinata, sở hữu con mắt Jougan và ấn diệt thần Karma.' },
    { name: 'Sarada Uchiha', role: 'Đồng đội', description: 'Con gái của Sasuke và Sakura, ước mơ trở thành Hokage, sở hữu Sharingan.' },
    { name: 'Mitsuki', role: 'Đồng đội', description: 'Con người nhân tạo được tạo ra bởi Orochimaru, sở hữu Tiên nhân thuật.' },
    { name: 'Kawaki', role: 'Đối thủ/Anh em', description: 'Vật chứa của Isshiki Otsutsuki, được Naruto nhận nuôi, sở hữu Karma.' },
    { name: 'Naruto Uzumaki', role: 'Hokage đệ Thất', description: 'Cha của Boruto, anh hùng của thế giới nhẫn giả, vật chứa của Cửu Vĩ Kurama.' },
    { name: 'Sasuke Uchiha', role: 'Sư phụ của Boruto', description: 'Cha của Sarada, nhẫn giả hỗ trợ Hokage, sở hữu Rinnegan và Sharingan.' },
    { name: 'Hinata Hyuga', role: 'Mẹ của Boruto', description: 'Vợ của Naruto, cựu công chúa tộc Hyuga, sở hữu Byakugan.' },
    { name: 'Sakura Uchiha', role: 'Mẹ của Sarada', description: 'Vợ của Sasuke, y nhẫn giả xuất sắc nhất làng Lá.' },
    { name: 'Himawari Uzumaki', role: 'Em gái Boruto', description: 'Con gái út của Naruto, sở hữu Byakugan từ khi còn rất nhỏ.' },
    { name: 'Konohamaru Sarutobi', role: 'Đội trưởng đội 7', description: 'Cháu trai của Hokage đệ Tam, người hướng dẫn của Boruto.' },
    { name: 'Shikamaru Nara', role: 'Cố vấn Hokage', description: 'Cánh tay phải của Naruto, thiên tài chiến thuật của làng Lá.' },
    { name: 'Ino Yamanaka', role: 'Trưởng đội cảm nhận', description: 'Bạn thân của Sakura, chuyên gia về tâm linh và cảm nhận.' },
    { name: 'Sai', role: 'Trưởng đội Anbu', description: 'Chồng của Ino, chuyên gia vẽ tranh nhẫn thuật.' },
    { name: 'Shikadai Nara', role: 'Bạn thân Boruto', description: 'Con trai của Shikamaru và Temari, sở hữu trí tuệ vượt trội.' },
    { name: 'Inojin Yamanaka', role: 'Đồng đội Shikadai', description: 'Con trai của Ino và Sai, kết hợp nhẫn thuật của cả cha và mẹ.' },
    { name: 'Chocho Akimichi', role: 'Đồng đội Shikadai', description: 'Con gái của Choji, sở hữu sức mạnh thể chất to lớn.' },
    { name: 'Sumire Kakei', role: 'Bạn học/Nhà khoa học', description: 'Cựu lớp trưởng, hiện làm việc tại đội Nhẫn cụ khoa học.' },
    { name: 'Denki Kaminarimon', role: 'Đồng đội Metal Lee', description: 'Thiên tài công nghệ, con trai của tập đoàn Kaminarimon.' },
    { name: 'Iwabee Yuino', role: 'Đồng đội Metal Lee', description: 'Chuyên gia về Thổ độn, có kỹ năng chiến đấu cận chiến tốt.' },
    { name: 'Metal Lee', role: 'Đồng đội Denki', description: 'Con trai của Rock Lee, chuyên gia thể thuật nhưng hay bị tâm lý.' },
    { name: 'Rock Lee', role: 'Thượng nhẫn', description: 'Cha của Metal Lee, bậc thầy thể thuật Bát Môn Độn Giáp.' },
    { name: 'Tenten', role: 'Thượng nhẫn', description: 'Chuyên gia sử dụng vũ khí và phong ấn.' },
    { name: 'Temari', role: 'Thượng nhẫn', description: 'Vợ của Shikamaru, đến từ làng Cát, chuyên gia Phong độn.' },
    { name: 'Gaara', role: 'Kazekage đệ Ngũ', description: 'Bạn thân của Naruto, người điều khiển cát của làng Cát.' },
    { name: 'Kankuro', role: 'Thượng nhẫn làng Cát', description: 'Anh trai của Gaara, bậc thầy điều khiển rối.' },
    { name: 'Shinki', role: 'Con nuôi Gaara', description: 'Thiên tài làng Cát, sở hữu Thiết sa (Cát sắt).' },
    { name: 'Moegi Kazamatsuri', role: 'Đội trưởng đội 10', description: 'Đồng đội cũ của Konohamaru, sở hữu Mộc độn.' },
    { name: 'Udon Ise', role: 'Đội trưởng đội 5', description: 'Đồng đội cũ của Konohamaru, chuyên gia Thủy độn.' },
    { name: 'Hanabi Hyuga', role: 'Đội trưởng đội 15', description: 'Dì của Boruto, người kế vị tộc Hyuga.' },
    { name: 'Hiashi Hyuga', role: 'Ông ngoại Boruto', description: 'Trưởng tộc Hyuga, ông ngoại nghiêm khắc nhưng yêu cháu.' },
    { name: 'Kakashi Hatake', role: 'Hokage đệ Lục', description: 'Cựu Hokage, người thầy huyền thoại của đội 7 cũ.' },
    { name: 'Tsunade', role: 'Hokage đệ Ngũ', description: 'Cựu Hokage, một trong Tam Nhẫn huyền thoại.' },
    { name: 'Orochimaru', role: 'Tam Nhẫn', description: 'Cha của Mitsuki, nhà khoa học điên đã cải tà quy chính.' },
    { name: 'Jigen', role: 'Thủ lĩnh Kara', description: 'Vật chứa của Isshiki Otsutsuki, kẻ thù cực kỳ hùng mạnh.' },
    { name: 'Koji Kashin', role: 'Thành viên Kara', description: 'Bản sao của Jiraiya, thâm nhập Kara với mục đích riêng.' },
    { name: 'Delta', role: 'Thành viên Kara', description: 'Người máy sinh học với sức mạnh tấn công đáng sợ.' },
    { name: 'Boro', role: 'Thành viên Kara', description: 'Kẻ sở hữu khả năng hồi phục và virus sinh học.' },
    { name: 'Code', role: 'Thành viên Kara', description: 'Kẻ trung thành cuối cùng của Isshiki, sở hữu Karma trắng.' },
    { name: 'Eida', role: 'Thành viên Kara', description: 'Sở hữu con mắt Senrigan có thể nhìn thấu mọi thứ.' },
    { name: 'Daemon', role: 'Em trai Eida', description: 'Sở hữu khả năng phản đòn mọi đòn tấn công nhắm vào mình.' },
    { name: 'Amado', role: 'Nhà khoa học Kara', description: 'Thiên tài đứng sau các công nghệ của Kara, đã đào tẩu sang làng Lá.' },
    { name: 'Momoshiki Otsutsuki', role: 'Gia tộc Otsutsuki', description: 'Kẻ đã để lại ấn Karma trên người Boruto.' },
    { name: 'Kinshiki Otsutsuki', role: 'Gia tộc Otsutsuki', description: 'Người hầu cận trung thành của Momoshiki.' },
    { name: 'Urashiki Otsutsuki', role: 'Gia tộc Otsutsuki', description: 'Kẻ săn lùng chakra của các vĩ thú.' }
  ]
};
