
import { FanficWork } from '../types';

export const FAIRY_TAIL: FanficWork = {
  id: 'fairy-tail',
  title: 'Fairy Tail',
  description: 'Câu chuyện về hội pháp sư Fairy Tail náo nhiệt và tình bạn gắn kết giữa các thành viên.',
  country: 'Nhật',
  plot: 'Lucy Heartfilia là một pháp sư trẻ tuổi đang trên đường tìm kiếm và gia nhập hội pháp sư nổi tiếng nhất vương quốc Fiore: Fairy Tail. Trên hành trình của mình, cô gặp Natsu Dragneel, một pháp sư sử dụng ma pháp diệt rồng lửa đang đi tìm cha nuôi là rồng Igneel. Cùng với chú mèo biết bay Happy, họ tạo thành một đội và thực hiện vô số nhiệm vụ nguy hiểm, đối mặt với các hội bóng tối và những bí ẩn về quá khứ của thế giới ma thuật.',
  worldSetting: 'Vương quốc Fiore, một thế giới nơi ma thuật là một phần của cuộc sống hàng ngày. Các pháp sư tập hợp lại thành các hội (Guild) để nhận nhiệm vụ và hỗ trợ lẫn nhau. Có nhiều loại ma thuật khác nhau như Ma pháp nguyên tố, Ma pháp triệu hồi, và đặc biệt là Ma pháp Diệt Rồng (Dragon Slayer).',
  characters: [
    { name: 'Natsu Dragneel', role: 'Nhân vật chính', description: 'Hỏa Sát Long Nhân, luôn tràn đầy năng lượng và yêu quý đồng đội.' },
    { name: 'Lucy Heartfilia', role: 'Nhân vật chính', description: 'Pháp sư Tinh Linh, người dẫn chuyện và là trái tim của nhóm.' },
    { name: 'Erza Scarlet', role: 'Cường giả', description: 'Nữ hoàng pháp sư với ma pháp Hoán Phục, nghiêm khắc nhưng ấm áp.' },
    { name: 'Gray Fullbuster', role: 'Đối thủ của Natsu', description: 'Pháp sư Băng Đúc, có thói quen cởi trần kỳ quặc.' },
    { name: 'Wendy Marvell', role: 'Thiên không Sát Long Nhân', description: 'Pháp sư trị thương nhỏ tuổi nhưng vô cùng mạnh mẽ.' },
    { name: 'Happy', role: 'Bạn đồng hành', description: 'Chú mèo tộc Exceed biết bay, luôn đi cùng Natsu.' },
    { name: 'Carla', role: 'Bạn đồng hành', description: 'Mèo tộc Exceed, bạn thân của Wendy, có khả năng tiên tri.' },
    { name: 'Gajeel Redfox', role: 'Thiết Sát Long Nhân', description: 'Cựu thành viên Phantom Lord, sau gia nhập Fairy Tail.' },
    { name: 'Panther Lily', role: 'Bạn đồng hành Gajeel', description: 'Chiến binh tộc Exceed với khả năng biến hình to lớn.' },
    { name: 'Juvia Lockser', role: 'Pháp sư Thủy', description: 'Yêu Gray điên cuồng, sức mạnh liên quan đến nước và mưa.' },
    { name: 'Laxus Dreyar', role: 'Lôi Sát Long Nhân', description: 'Cháu trai của hội trưởng Makarov, sở hữu sức mạnh sấm sét.' },
    { name: 'Mirajane Strauss', role: 'Nữ thần Fairy Tail', description: 'Sở hữu ma pháp Chiếm Hữu (Take Over) quỷ dữ.' },
    { name: 'Elfman Strauss', role: 'Thành viên', description: 'Em trai Mirajane, luôn miệng nói về "Đàn ông".' },
    { name: 'Lisanna Strauss', role: 'Thành viên', description: 'Em gái út nhà Strauss, bạn thanh mai trúc mã của Natsu.' },
    { name: 'Cana Alberona', role: 'Pháp sư bài', description: 'Con gái của Gildarts, tửu lượng cực cao.' },
    { name: 'Gildarts Clive', role: 'Pháp sư mạnh nhất', description: 'Cha của Cana, sở hữu ma pháp Phân Tách cực mạnh.' },
    { name: 'Makarov Dreyar', role: 'Hội trưởng', description: 'Người đứng đầu Fairy Tail, coi các thành viên như con cái.' },
    { name: 'Levy McGarden', role: 'Pháp sư ký tự', description: 'Thông minh, mọt sách, có tình cảm với Gajeel.' },
    { name: 'Jet', role: 'Thành viên', description: 'Thành viên đội Shadow Gear, sở hữu tốc độ cao.' },
    { name: 'Droy', role: 'Thành viên', description: 'Thành viên đội Shadow Gear, sử dụng ma pháp thực vật.' },
    { name: 'Alzack Connell', role: 'Xạ thủ', description: 'Sử dụng súng ma pháp, chồng của Bisca.' },
    { name: 'Bisca Connell', role: 'Xạ thủ', description: 'Sử dụng súng ma pháp, vợ của Alzack.' },
    { name: 'Asuka Connell', role: 'Thành viên nhỏ tuổi', description: 'Con gái của Alzack và Bisca.' },
    { name: 'Romeo Conbolt', role: 'Pháp sư lửa trẻ', description: 'Thần tượng Natsu, con trai của Macao.' },
    { name: 'Macao Conbolt', role: 'Hội trưởng đệ Tứ', description: 'Sử dụng lửa tím, cha của Romeo.' },
    { name: 'Wakaba Mine', role: 'Thành viên kỳ cựu', description: 'Sử dụng ma pháp khói, bạn thân của Macao.' },
    { name: 'Freed Justine', role: 'Đội Lôi Thần', description: 'Chuyên gia về thuật ấn ký, cực kỳ trung thành với Laxus.' },
    { name: 'Bickslow', role: 'Đội Lôi Thần', description: 'Sử dụng ma pháp điều khiển linh hồn và hình nộm.' },
    { name: 'Evergreen', role: 'Đội Lôi Thần', description: 'Sở hữu đôi mắt hóa đá, có tình cảm với Elfman.' },
    { name: 'Jellal Fernandes', role: 'Pháp sư Thiên Thể', description: 'Bạn thơ ấu của Erza, thủ lĩnh hội Crime Sorcière.' },
    { name: 'Ultear Milkovich', role: 'Pháp sư Thời Gian', description: 'Con gái của Ur, từng là phản diện sau đó cải tà.' },
    { name: 'Meredy', role: 'Pháp sư Liên Kết', description: 'Con nuôi của Ultear, thành viên Crime Sorcière.' },
    { name: 'Zeref Dragneel', role: 'Pháp sư đen tối', description: 'Pháp sư bất tử và là anh trai của Natsu.' },
    { name: 'Mavis Vermillion', role: 'Hội trưởng đầu tiên', description: 'Người sáng lập Fairy Tail, chiến lược gia tài ba.' },
    { name: 'Sting Eucliffe', role: 'Bạch Sát Long Nhân', description: 'Hội trưởng hội Sabertooth, ngưỡng mộ Natsu.' },
    { name: 'Rogue Cheney', role: 'Ảnh Sát Long Nhân', description: 'Thành viên Sabertooth, trầm tính và lạnh lùng.' },
    { name: 'Lector', role: 'Mèo Sabertooth', description: 'Bạn đồng hành của Sting.' },
    { name: 'Frosch', role: 'Mèo Sabertooth', description: 'Bạn đồng hành của Rogue, luôn mặc bộ đồ ếch.' },
    { name: 'Minerva Orland', role: 'Tiểu thư Sabertooth', description: 'Sở hữu ma pháp không gian mạnh mẽ.' },
    { name: 'Kagura Mikazuchi', role: 'Pháp sư Mermaid Heel', description: 'Kiếm sĩ tài năng, em gái của Simon.' },
    { name: 'Ichiya Vandalay Kotobuki', role: 'Blue Pegasus', description: 'Pháp sư sử dụng nước hoa (Parfum) kỳ lạ.' },
    { name: 'Lyon Vastia', role: 'Lamia Scale', description: 'Sư huynh của Gray, sử dụng Băng Đúc động.' },
    { name: 'Sherry Blendy', role: 'Lamia Scale', description: 'Sử dụng ma pháp điều khiển vật thể.' },
    { name: 'Sherria Blendy', role: 'Thiên không Diệt Thần Nhân', description: 'Em họ của Sherry, bạn thân của Wendy.' },
    { name: 'Jura Neekis', role: 'Thập Đại Thánh Pháp Sư', description: 'Pháp sư Thổ mạnh mẽ của hội Lamia Scale.' }
  ]
};
