
import { FanficWork } from '../types';

export const JINDO: FanficWork = {
  id: 'jindo',
  title: 'Jindo (Kattobi Itto)',
  description: 'Hành trình bóng đá đầy hài hước và nhiệt huyết của cậu bé lùn Jindo và các đồng đội.',
  country: 'Nhật',
  plot: 'Jindo (Itto Katori) là một cậu bé có chiều cao khiêm tốn nhưng sở hữu kỹ thuật bóng đá siêu hạng và tính cách vô cùng quậy phá. Sau khi từ Trung Quốc trở về Nhật Bản, cậu gia nhập đội bóng trường trung học Seiga. Tại đây, cậu gặp lại người bạn cũ Yara (Yura) và cùng các đồng đội khác tạo nên những trận cầu nảy lửa, hài hước nhưng cũng không kém phần kịch tính để chinh phục chức vô địch quốc gia.',
  worldSetting: 'Thế giới bóng đá học đường Nhật Bản những năm 90. Các trận đấu không chỉ là kỹ thuật mà còn là những pha va chạm nảy lửa, những chiêu trò hài hước và tinh thần đồng đội bất diệt.',
  characters: [
    { name: 'Jindo (Itto Katori)', role: 'Nhân vật chính', description: 'Cậu bé lùn, quậy phá, giỏi võ thuật và có kỹ thuật bóng đá quái chiêu.' },
    { name: 'Yara (Mao Yura)', role: 'Đội trưởng Seiga', description: 'Bạn thân và cũng là đối thủ của Jindo, sở hữu cú sút sấm sét.' },
    { name: 'Ken (Kenji Tsukawaki)', role: 'Thủ môn Seiga', description: 'Thủ môn tài năng với khả năng phản xạ tuyệt vời.' },
    { name: 'Taburo (Taburo Oda)', role: 'Tiền đạo Seiga', description: 'Cầu thủ to con, có sức mạnh tì đè tốt.' },
    { name: 'Hanyu (Seiga Hanyu)', role: 'Tiền đạo Seiga', description: 'Cầu thủ có cú sút cực mạnh nhưng độ chính xác... tùy hứng.' },
    { name: 'Nê (Nezu)', role: 'Hậu vệ Seiga', description: 'Thành viên nhóm "Ba con hủi", hậu vệ lì lợm.' },
    { name: 'Chika', role: 'Hậu vệ Seiga', description: 'Thành viên nhóm "Ba con hủi", chuyên gia xoạc bóng.' },
    { name: 'Hiro', role: 'Hậu vệ Seiga', description: 'Thành viên nhóm "Ba con hủi", phối hợp ăn ý với Nê và Chika.' },
    { name: 'Satomi', role: 'Quản lý đội bóng', description: 'Cô gái xinh đẹp, luôn đau đầu vì những trò quậy của Jindo.' },
    { name: 'Huấn luyện viên Seiga', role: 'HLV', description: 'Người dẫn dắt đội bóng Seiga vượt qua các thử thách.' },
    { name: 'Ryuji', role: 'Đối thủ', description: 'Cầu thủ tài năng của đội bóng đối địch.' },
    { name: 'Akira', role: 'Đối thủ', description: 'Tiền vệ hào hoa với kỹ thuật cá nhân điêu luyện.' },
    { name: 'Shingo', role: 'Thành viên Seiga', description: 'Tiền vệ cần cù, luôn hỗ trợ đồng đội.' },
    { name: 'Makoto', role: 'Thành viên Seiga', description: 'Hậu vệ chắc chắn của đội.' },
    { name: 'Takeshi', role: 'Thành viên Seiga', description: 'Cầu thủ có tốc độ tốt.' },
    { name: 'Kazu', role: 'Thành viên Seiga', description: 'Tiền vệ cánh năng nổ.' },
    { name: 'Toshi', role: 'Thành viên Seiga', description: 'Dự bị chiến lược của đội.' },
    { name: 'Jun', role: 'Thành viên Seiga', description: 'Cầu thủ có khả năng đọc trận đấu tốt.' },
    { name: 'Shin', role: 'Thành viên Seiga', description: 'Hậu vệ trẻ triển vọng.' },
    { name: 'Goro', role: 'Đối thủ', description: 'Hậu vệ to con của đội bạn.' },
    { name: 'Jiro', role: 'Đối thủ', description: 'Tiền đạo nhanh nhẹn.' },
    { name: 'Saburo', role: 'Đối thủ', description: 'Tiền vệ trung tâm mạnh mẽ.' },
    { name: 'Shiro', role: 'Đối thủ', description: 'Thủ môn có sải tay dài.' },
    { name: 'Hideo', role: 'Đối thủ', description: 'Chuyên gia sút phạt.' },
    { name: 'Masao', role: 'Đối thủ', description: 'Cầu thủ chơi bóng bổng tốt.' },
    { name: 'Kazuo', role: 'Đối thủ', description: 'Tiền vệ đánh chặn hiệu quả.' },
    { name: 'Tetsuo', role: 'Đối thủ', description: 'Hậu vệ cánh có khả năng leo biên.' },
    { name: 'Yoshio', role: 'Đối thủ', description: 'Tiền đạo có khả năng dứt điểm đa dạng.' },
    { name: 'Kunio', role: 'Đối thủ', description: 'Tiền vệ kiến thiết.' },
    { name: 'Mikio', role: 'Đối thủ', description: 'Thủ môn dự bị.' },
    { name: 'Yukio', role: 'Đối thủ', description: 'Hậu vệ trẻ.' },
    { name: 'Akio', role: 'Đối thủ', description: 'Tiền đạo trẻ.' },
    { name: 'Norio', role: 'Đối thủ', description: 'Tiền vệ trẻ.' },
    { name: 'Morio', role: 'Đối thủ', description: 'Hậu vệ kỳ cựu.' },
    { name: 'Tokio', role: 'Đối thủ', description: 'Tiền đạo kỳ cựu.' },
    { name: 'Sakio', role: 'Đối thủ', description: 'Tiền vệ kỳ cựu.' },
    { name: 'Takio', role: 'Đối thủ', description: 'Thủ môn kỳ cựu.' },
    { name: 'Fumio', role: 'Đối thủ', description: 'Huấn luyện viên đội bạn.' },
    { name: 'Ông Katori', role: 'Cha Jindo', description: 'Người truyền cảm hứng võ thuật và tính cách quậy phá cho Jindo.' },
    { name: 'Chị của Yara', role: 'Người thân', description: 'Luôn ủng hộ em trai và đội bóng.' }
  ]
};
