
import { FanficWork } from '../types';

export const TSUBASA: FanficWork = {
  id: 'tsubasa',
  title: 'Captain Tsubasa',
  description: 'Huyền thoại bóng đá về Tsubasa Ozora và ước mơ đưa bóng đá Nhật Bản vươn tầm thế giới.',
  country: 'Nhật',
  plot: 'Tsubasa Ozora là một cậu bé có niềm đam mê mãnh liệt với bóng đá từ nhỏ. Sau khi chuyển đến Nankatsu, cậu gặp gỡ những người bạn và đối thủ tài năng như Genzo Wakabayashi, Kojiro Hyuga, Taro Misaki. Dưới sự dẫn dắt của cựu siêu sao Roberto Hongo, Tsubasa cùng các đồng đội đã vượt qua nhiều giải đấu học đường và sau đó là vươn ra thế giới, thi đấu tại các câu lạc bộ hàng đầu châu Âu và khoác áo đội tuyển quốc gia Nhật Bản.',
  worldSetting: 'Thế giới bóng đá chuyên nghiệp, từ các giải học đường Nhật Bản đến các sân vận động rực lửa tại Brazil, Tây Ban Nha, Ý. Nơi đây tôn vinh những kỹ thuật siêu đẳng, tinh thần thể thao cao thượng và khát vọng chinh phục đỉnh cao.',
  characters: [
    { name: 'Tsubasa Ozora', role: 'Nhân vật chính', description: 'Thiên tài bóng đá, luôn coi quả bóng là bạn.' },
    { name: 'Genzo Wakabayashi', role: 'Thủ môn huyền thoại', description: 'Thủ môn số 1, có khả năng cản phá mọi cú sút từ ngoài vòng cấm.' },
    { name: 'Kojiro Hyuga', role: 'Đối thủ lớn nhất', description: 'Tiền đạo sức mạnh với cú sút Mãnh Hổ (Tiger Shot).' },
    { name: 'Taro Misaki', role: 'Cặp bài trùng', description: 'Tiền vệ tài hoa, phối hợp ăn ý nhất với Tsubasa.' },
    { name: 'Ken Wakashimazu', role: 'Thủ môn Karate', description: 'Thủ môn có phong cách bắt bóng kết hợp võ thuật.' },
    { name: 'Jun Misugi', role: 'Hoàng tử sân cỏ', description: 'Thiên tài chiến thuật nhưng bị bệnh tim bẩm sinh.' },
    { name: 'Hikaru Matsuyama', role: 'Đại bàng vùng tuyết', description: 'Cầu thủ có tinh thần bền bỉ và cú sút Đại Bàng.' },
    { name: 'Ryo Ishizaki', role: 'Hậu vệ dũng cảm', description: 'Bạn thân của Tsubasa, nổi tiếng với pha cản bóng bằng mặt.' },
    { name: 'Shun Nitta', role: 'Tiền đạo tốc độ', description: 'Sở hữu cú sút Ưng Phi (Falcon Shot).' },
    { name: 'Takeshi Sawada', role: 'Tiền vệ trẻ', description: 'Cấp dưới trung thành và ăn ý của Hyuga.' },
    { name: 'Kazuo Tachibana', role: 'Anh em sinh đôi', description: 'Nổi tiếng với các pha phối hợp nhào lộn trên không.' },
    { name: 'Masao Tachibana', role: 'Anh em sinh đôi', description: 'Cùng với Kazuo tạo nên cặp đôi nhào lộn kỳ ảo.' },
    { name: 'Hiroshi Jito', role: 'Hậu vệ khổng lồ', description: 'Sở hữu sức mạnh thể chất vượt trội.' },
    { name: 'Mitsuru Sano', role: 'Tiền đạo lắt léo', description: 'Phối hợp ăn ý với Jito nhờ sự nhanh nhẹn.' },
    { name: 'Makoto Soda', role: 'Sát thủ vùng biên', description: 'Hậu vệ có cú sút hình lưỡi liềm (Razor Shot).' },
    { name: 'Shingo Aoi', role: 'Hoàng tử mặt trời', description: 'Tiền vệ năng nổ, thi đấu tại Ý.' },
    { name: 'Mamoru Izawa', role: 'Tiền vệ Nankatsu', description: 'Chuyên gia không chiến của bộ tứ Nankatsu.' },
    { name: 'Teppei Kisugi', role: 'Tiền đạo Nankatsu', description: 'Thành viên bộ tứ Nankatsu.' },
    { name: 'Hajime Taki', role: 'Tiền đạo cánh Nankatsu', description: 'Chuyên gia leo biên của bộ tứ Nankatsu.' },
    { name: 'Shingo Takasugi', role: 'Hậu vệ Nankatsu', description: 'Hậu vệ to con với những cú ném biên rất mạnh.' },
    { name: 'Yuzuru Morisaki', role: 'Thủ môn dự bị', description: 'Luôn nỗ lực hết mình để bảo vệ khung thành.' },
    { name: 'Hanji Urabe', role: 'Hậu vệ đa năng', description: 'Cầu thủ có lối chơi quyết liệt.' },
    { name: 'Roberto Hongo', role: 'Sư phụ', description: 'Cựu tuyển thủ Brazil, người thầy đầu tiên của Tsubasa.' },
    { name: 'Sanae Nakazawa', role: 'Vợ Tsubasa', description: 'Trưởng đội cổ vũ, luôn sát cánh bên Tsubasa.' },
    { name: 'Yayoi Aoba', role: 'Bạn gái Misugi', description: 'Luôn lo lắng và ủng hộ Misugi.' },
    { name: 'Yoshiko Matsuyama', role: 'Bạn gái Matsuyama', description: 'Người tặng băng đội đầu cho Matsuyama.' },
    { name: 'Maki Akamine', role: 'Bạn gái Hyuga', description: 'Vận động viên bóng mềm, người truyền cảm hứng cho Hyuga.' },
    { name: 'Munemasa Katagiri', role: 'Trinh sát viên', description: 'Người luôn tìm kiếm và bồi dưỡng tài năng cho bóng đá Nhật.' },
    { name: 'Tatsuo Mikami', role: 'HLV Wakabayashi', description: 'Người thầy nghiêm khắc của thủ môn thiên tài.' },
    { name: 'Kozo Kira', role: 'HLV Hyuga', description: 'Người dạy cho Hyuga lối đá tấn công mãnh liệt.' },
    { name: 'Karl-Heinz Schneider', role: 'Hoàng đế Đức', description: 'Tiền đạo số 1 châu Âu, đối thủ lớn của Tsubasa.' },
    { name: 'Hermann Kaltz', role: 'Tiền vệ Đức', description: 'Chuyên gia phòng ngự với lối chơi thông minh.' },
    { name: 'Franz Schester', role: 'Kiến thiết Đức', description: 'Tiền vệ hào hoa của đội tuyển Đức.' },
    { name: 'Manfred Margus', role: 'Tiền đạo Đức', description: 'Chuyên gia đánh đầu.' },
    { name: 'Deuter Muller', role: 'Thủ môn thép', description: 'Thủ môn khổng lồ của đội tuyển Đức.' },
    { name: 'Carlos Santana', role: 'Cyborg bóng đá', description: 'Thiên tài Brazil, đối thủ định mệnh của Tsubasa.' },
    { name: 'Natureza', role: 'Vua bóng đá', description: 'Thiên tài ẩn dật của Brazil với kỹ năng siêu phàm.' },
    { name: 'Rivaul', role: 'Ngôi sao Barcelona', description: 'Đồng đội và là người thầy của Tsubasa tại Barca.' },
    { name: 'Juan Diaz', role: 'Thiên tài Argentina', description: 'Sở hữu kỹ thuật cá nhân điêu luyện như Maradona.' },
    { name: 'Alan Pascal', role: 'Đồng đội Diaz', description: 'Bạn thân và là người phối hợp ăn ý với Diaz.' },
    { name: 'Elle Sid Pierre', role: 'Hào hoa nước Pháp', description: 'Thủ lĩnh đội tuyển Pháp với lối đá nghệ thuật.' },
    { name: 'Louis Napoleon', role: 'Tiền đạo Pháp', description: 'Sở hữu cú sút Pháo Hoa (Cannon Shot).' },
    { name: 'Gino Hernandez', role: 'Thủ môn Ý', description: 'Thủ môn xuất sắc nhất châu Âu với đôi bàn tay vàng.' },
    { name: 'Salvatore Gentile', role: 'Hậu vệ Ý', description: 'Hậu vệ quét tài năng của đội tuyển Ý.' },
    { name: 'Stefan Levin', role: 'Thần hủy diệt Thụy Điển', description: 'Sở hữu cú sút Levin Shot đầy uy lực.' }
  ]
};
